name: Build and Push to ECR

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'ui/**'
      - 'backend/**'
      - '.github/workflows/**'
      - 'infra/docker/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: thesis
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build and push UI
          docker build -f infra/docker/ui.Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:ui .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:ui
          
#          # Build and push API
#          docker build -f infra/docker/api.Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:api .
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:api

      - name: Force ECS deployment
        run: |
          aws ecs update-service --cluster thesis --service thesis-ui --force-new-deployment
#          aws ecs update-service --cluster thesis --service thesis-api --force-new-deployment
